export enum RequestTypes {
  REG = 'reg',
  UPDATE_USERS = 'update_winners',
  ADD_USER_TO_ROOM = "add_user_to_room",
  CREATE_ROOM = 'create_room',
  CREATE_GAME = 'create_game',
  UPDATE_ROOM = 'update_room',
  UPDATE_WINNERS = 'update_winners',
  ADD_SHIPS = 'add_ships',
  START_GAME = 'start_game',
  ATTACK = 'attack',
  RANDOM_ATTACK = 'randomAttack', 
  TURN = 'turn',
  FINISH = 'finish',
}